# Generated by Django 3.0.8 on 2021-08-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='post_type',
            field=models.CharField(choices=[('Technical', 'Technical'), ('General_Knowledge', 'General Knowledge'), ('Sports', 'Sports'), ('Food', 'Food'), ('Political', 'Political'), ('Entertainment', 'Entertainment')], default='select one', max_length=100),
        ),
    ]
